version: '3.4'

#Named Volumes
volumes:
    vivapets-akeneo-mysql-data:
        driver: local
    vivapets-akeneo-elasticsearch-data:
        driver: local

networks:
    vivapets-akeneo-internal-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.22.231.0/24
    vivapets-proxy-network:
        external:
            name: vivapets-nginx-proxy-net


services:
  vivapets-akeneo-php:
    build:
        context: .
        dockerfile: ./docker/app/Dockerfile
        args:
            UID: ${USERID:-1000}
            GID: ${GID:-1000}
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=pim-docker-cli'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - './:/srv/pim'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/pim'
    command: 'php'
    networks:
      - 'vivapets-akeneo-internal-network'

  vivapets-akeneo-fpm:
    build:
        context: .
        dockerfile: ./docker/app/Dockerfile
        args:
            UID: ${USERID:-1000}
            GID: ${GID:-1000}
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      BEHAT_TMPDIR: '/srv/pim/var/cache/tmp'
      BEHAT_SCREENSHOT_PATH: '/srv/pim/var/tests/screenshots'
      PHP_IDE_CONFIG: 'serverName=pim-docker-web'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
      BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID:-client_id}'
      BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN:-client_token}'
    volumes:
      - './:/srv/pim'
      - './docker/supervisor:/etc/supervisor'
    working_dir: '/srv/pim'
    command: '/usr/bin/supervisord -n'
    networks:
      - 'vivapets-akeneo-internal-network'

  vivapets-akeneo-node:
    image: 'akeneo/node:10'
    environment:
      YARN_CACHE_FOLDER: '/home/node/.yarn'
    volumes:
      - './:/srv/pim'
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/node/.yarn'
    working_dir: '/srv/pim'
    networks:
      - 'vivapets-akeneo-internal-network'

  vivapets-akeneo-selenium:
    image: 'selenium/standalone-firefox-debug:2.53.1-beryllium'
    volumes:
      - './:/srv/pim:ro'
#    ports:
#      - '${DOCKER_PORT_SELENIUM:-5910}:5900'
    networks:
      - 'vivapets-akeneo-internal-network'

  vivapets-akeneo-httpd:
    image: 'httpd:2.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
    depends_on:
      - 'vivapets-akeneo-fpm'
#    ports:
#      - '${DOCKER_PORT_HTTP:-8080}:80'
    volumes:
      - './:/srv/pim:ro'
      - './docker/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/akeneo.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'vivapets-akeneo-internal-network'
      - 'vivapets-proxy-network'

  vivapets-akeneo-mysql:
    image: 'mysql:8.0.18'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - vivapets-akeneo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: '${APP_DATABASE_USER}'
      MYSQL_DATABASE: '${APP_DATABASE_NAME}'
      MYSQL_PASSWORD: '${APP_DATABASE_PASSWORD}'
#    ports:
#      - '${DOCKER_PORT_MYSQL:-33006}:3306'
    networks:
      - 'vivapets-akeneo-internal-network'

  vivapets-akeneo-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.1'
    volumes:
      - vivapets-akeneo-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx512m}'
      discovery.type: 'single-node'
#    ports:
#      - '${DOCKER_PORT_ELASTICSEARCH:-9210}:9200'
    networks:
      - 'vivapets-akeneo-internal-network'

  vivapets-akeneo-object-storage:
    image: 'minio/minio'
    entrypoint: '/bin/sh -c "mkdir -p /data/asset /data/archive /data/catalog/ /data/jobs && minio server /data"'
    environment:
      MINIO_ACCESS_KEY: 'AKENEO_OBJECT_STORAGE_ACCESS_KEY'
      MINIO_SECRET_KEY: 'AKENEO_OBJECT_STORAGE_SECRET_KEY'
#    ports:
#      - '${DOCKER_PORT_OBJECT_STORAGE:-9090}:9000'
    networks:
      - 'vivapets-akeneo-internal-network'

  vivapets-akeneo-blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID:-server_id}'
      BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN:-server_token}'
    networks:
      - 'vivapets-akeneo-internal-network'
